# Generated by Django 5.2.3 on 2026-01-02 23:14

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(max_length=4096, validators=[django.core.validators.URLValidator()])),
                ('short_code', models.CharField(editable=False, max_length=8, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data/hora em que o link expira', null=True)),
                ('created_by_ip', models.GenericIPAddressField(blank=True, help_text='IP do usuário anônimo que criou a URL', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
