# Generated by Django 5.2.1 on 2025-06-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(default='f881f23b-1c16-43f9-83e9-64d3b6260316', max_length=8, unique=True),
        ),
    ]
