# Generated by Django 5.2.3 on 2025-10-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_accessevent_id_remove_url_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessevent',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='uuid',
            new_name='id',
        ),
    ]
