# Generated by Django 5.2.3 on 2025-06-16 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_alter_url_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
