# Generated by Django 5.2.3 on 2026-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
