# Generated by Django 5.2.3 on 2026-02-24 13:27

from django.db import migrations


def forwards(apps, schema_editor):
    Url = apps.get_model("converter", "Url")
    UrlMetadata = apps.get_model("converter", "UrlMetadata")

    for url in Url.objects.all().iterator():
        meta, _ = UrlMetadata.objects.get_or_create(url=url)
        meta.is_direct = url.is_direct
        meta.save(update_fields=["is_direct"])


def backwards(apps, schema_editor):
    UrlMetadata = apps.get_model("converter", "UrlMetadata")

    for meta in UrlMetadata.objects.select_related("url").iterator():
        if hasattr(meta.url, "is_direct"):
            meta.url.is_direct = meta.is_direct
            meta.url.save(update_fields=["is_direct"])


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0004_urlmetadata"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
