# Generated by Django 5.2.3 on 2025-06-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_alter_url_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created_by_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP do usuário anônimo que criou a URL', null=True),
        ),
    ]
