# Generated by Django 5.2.3 on 2026-02-24 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0005_migrate_url_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="is_direct",
        ),
    ]
