# Generated by Django 5.2.3 on 2025-08-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_url_created_by_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.PositiveBigIntegerField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.url')),
            ],
        ),
    ]
