# Generated by Django 5.2.3 on 2026-02-26 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_remove_url_is_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='url',
            name='sequence',
            field=models.PositiveBigIntegerField(auto_created=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accessevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
