# Generated by Django 5.2.3 on 2026-02-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0007_remove_url_expires_at_url_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'url_sequence',
            },
        ),
        migrations.AlterField(
            model_name='url',
            name='created_by_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
