# Generated by Django 5.2.3 on 2026-04-16 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0009_remove_url_sequence_accessevent_browser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='sequence',
        ),
    ]
