# Generated by Django 5.2.3 on 2025-10-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='enable_custom_domains',
            new_name='enable_conditional_redirect',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='monthly_coins',
            new_name='monthly_credits',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_urls',
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_expiration_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_interstitial_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='enable_link_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
