# Generated by Django 5.2.3 on 2025-10-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_enable_custom_domains_plan_enable_conditional_redirect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='enable_advanced_stats',
            new_name='advanced_stats',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='enable_conditional_redirect',
            new_name='conditional_redirect',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='enable_interstitial_page',
            new_name='disable_interstitial_page',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='enable_expiration_date',
            new_name='longtime_expiration_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='enable_link_expiration',
        ),
    ]
