# Generated by Django 5.2.3 on 2026-01-03 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.userwallet'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['external_reference'], name='billing_wal_externa_5d3fa1_idx'),
        ),
    ]
