# Generated by Django 5.2.3 on 2025-10-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_enable_advanced_stats_plan_advanced_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
    ]
