# Generated by Django 5.2.3 on 2026-01-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_wallettransaction_wallet_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wallettransaction',
            name='billing_wal_externa_5d3fa1_idx',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.userwallet'),
        ),
    ]
