# Generated by Django 5.2.3 on 2025-10-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_priority_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
