# Generated by Django 5.2.3 on 2026-02-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_wallettransaction_billing_wal_externa_5d3fa1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
