# Generated by Django 5.2.3 on 2025-12-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_wallettransaction_external_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('success', 'Concluída'), ('failed', 'Falhou'), ('refunded', 'Estornada')], default='pending', max_length=10),
        ),
    ]
