# Generated by Django 5.2.3 on 2025-06-16 01:09

import apps.account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=apps.account.utils.ProfileUtils.get_random_profile_image, upload_to=apps.account.utils.ProfileUtils.generate_image_path),
        ),
    ]
