# Generated by Django 5.2.3 on 2026-01-02 23:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('show_only_once', models.BooleanField(default=False, verbose_name='Exibir apenas uma vez por usuário')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da exibição')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim da exibição (opcional)')),
                ('display_order', models.PositiveIntegerField(default=0, unique=True, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Novidade',
                'verbose_name_plural': 'Novidades',
                'ordering': ['display_order', '-start_at'],
            },
        ),
    ]
