# Generated by Django 5.2.3 on 2025-11-28 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "show_only_once",
                    models.BooleanField(
                        default=False, verbose_name="Exibir apenas uma vez por usuário"
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Início da exibição"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim da exibição (opcional)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem de exibição"),
                ),
            ],
            options={
                "verbose_name": "Novidade",
                "verbose_name_plural": "Novidades",
                "ordering": ["display_order", "-start_at"],
            },
        ),
    ]
