# Generated by Django 5.2.3 on 2025-12-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='display_order',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Ordem de exibição'),
        ),
    ]
