# Generated by Django 5.2.3 on 2026-01-02 20:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('rollout_percentage', models.PositiveIntegerField(default=100)),
                ('superuser_only', models.BooleanField(default=False)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='feature_flags', to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
