name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./src

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update packages
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
          
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: './src/pyproject.toml'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install the project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run Django tests
        run: .venv/bin/python manage.py test
